
CREATE TABLE IF NOT EXISTS homepage_content (
  id INT PRIMARY KEY DEFAULT 1,
  stats_churches TEXT NOT NULL,
  stats_pastors TEXT NOT NULL,
  stats_lives TEXT NOT NULL,
  stats_countries TEXT NOT NULL,
  hero_headline TEXT NOT NULL,
  hero_subheadline TEXT NOT NULL,
  hero_image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE homepage_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on homepage_content" ON homepage_content FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert homepage_content" ON homepage_content FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update homepage_content" ON homepage_content FOR UPDATE USING (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  is_major BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on events" ON events FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert events" ON events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update events" ON events FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete events" ON events FOR DELETE USING (auth.role() = 'authenticated');

-- Sermons Table
CREATE TABLE IF NOT EXISTS sermons (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  speaker TEXT NOT NULL,
  date TEXT,
  duration TEXT,
  "youtubeId" TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE sermons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on sermons" ON sermons FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert sermons" ON sermons FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update sermons" ON sermons FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete sermons" ON sermons FOR DELETE USING (auth.role() = 'authenticated');

-- Books Table
CREATE TABLE IF NOT EXISTS books (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  category TEXT,
  pages INT,
  downloads TEXT,
  format TEXT,
  description TEXT,
  cover TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE books ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on books" ON books FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert books" ON books FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update books" ON books FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete books" ON books FOR DELETE USING (auth.role() = 'authenticated');

-- Prayers Table
CREATE TABLE IF NOT EXISTS prayers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  request TEXT NOT NULL,
  date TEXT,
  status TEXT,
  branch TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE prayers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on prayers" ON prayers FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert prayers" ON prayers FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update prayers" ON prayers FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete prayers" ON prayers FOR DELETE USING (auth.role() = 'authenticated');

-- Branches Table
CREATE TABLE IF NOT EXISTS branches (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  pastor TEXT,
  members INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on branches" ON branches FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert branches" ON branches FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update branches" ON branches FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete branches" ON branches FOR DELETE USING (auth.role() = 'authenticated');

-- Storage Buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('media', 'media', true) ON CONFLICT DO NOTHING;

CREATE POLICY "Allow public read access on media" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "Allow authenticated users to upload media" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete media" ON storage.objects FOR DELETE USING (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update media" ON storage.objects FOR UPDATE USING (bucket_id = 'media' AND auth.role() = 'authenticated');

-- Seed Data
INSERT INTO homepage_content (id, stats_churches, stats_pastors, stats_lives, stats_countries, hero_headline, hero_subheadline, hero_image_url) VALUES
(1, '40+', '100+', '10k+', '12+', 'Born of God', 'Equipping pastors globally and transforming lives through the power and love of Christ.', 'https://picsum.photos/seed/church/1920/1080')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sermons (title, speaker, date, duration, "youtubeId") VALUES
('The Power of Sonship', 'Apostle John Doe', 'Oct 22, 2023', '45 mins', 'dQw4w9WgXcQ'),
('Faith That Moves Mountains', 'Pastor Jane Smith', 'Oct 15, 2023', '52 mins', 'dQw4w9WgXcQ'),
('Walking in Divine Purpose', 'Apostle John Doe', 'Oct 08, 2023', '60 mins', 'dQw4w9WgXcQ')
ON CONFLICT DO NOTHING;

INSERT INTO books (id, title, author, category, pages, downloads, format, description) VALUES
('b1', 'Foundations of Faith', 'Apostle John Doe', 'Discipleship', 120, '15.2k', 'PDF', 'A core guide to Christian faith.'),
('b2', 'The Prayer Driven Church', 'Pastor Jane Doe', 'Prayer', 210, '8.4k', 'EPUB', 'Developing church-wide prayer strategy.'),
('b3', 'Marriage By Design', 'Rev. Mark Smith', 'Marriage', 185, '10.1k', 'PDF', 'Biblical guide to healthy relationships.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO events (title, date, time, location, description, is_major) VALUES
('Global Leadership Summit 2026', 'Aug 15, 2026', '09:00 AM', 'Nairobi HQ & Online', 'A gathering of apostolic leaders and marketplace ministers for spiritual alignment and strategic equipping.', true),
('Anointed Fire & Power Night', 'Sep 04, 2026', '08:00 PM', 'London Covenant Dome', 'A night of deep worship, prophetic declarations, and tangible manifestations of the Holy Spirit.', false),
('International Discipleship Conference', 'Oct 12, 2026', '10:00 AM', 'Johannesburg Center', 'Immersive workshops and teachings on building strong, Christ-centered foundations in modern society.', false)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- ADMIN ACCOUNT CREATION FOR SUPABASE AUTH
-- Run this in the Supabase SQL Editor to create an admin user safely
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
  new_user_id uuid := gen_random_uuid();
  admin_email text := 'admin@bornofgod.org';
  admin_password text := 'YourSecurePassword123!';
BEGIN
  -- Check if user already exists
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = admin_email) THEN
    -- Insert user into auth.users
    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      recovery_sent_at,
      last_sign_in_at,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin,
      created_at,
      updated_at,
      phone,
      phone_confirmed_at,
      confirmation_token,
      email_change,
      email_change_token_new,
      recovery_token
    ) VALUES (
      '00000000-0000-0000-0000-000000000000',
      new_user_id,
      'authenticated',
      'authenticated',
      admin_email,
      crypt(admin_password, gen_salt('bf')),
      NOW(),
      NOW(),
      NOW(),
      '{"provider": "email", "providers": ["email"]}',
      '{"name": "Admin User", "role": "Super Administrator"}',
      FALSE,
      NOW(),
      NOW(),
      NULL,
      NULL,
      '',
      '',
      '',
      ''
    );

    -- Create associated identity record for email provider authentication
    INSERT INTO auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      provider_id,
      last_sign_in_at,
      created_at,
      updated_at
    ) VALUES (
      new_user_id,
      new_user_id,
      format('{"sub":"%s","email":"%s"}', new_user_id, admin_email)::jsonb,
      'email',
      new_user_id::text,
      NOW(),
      NOW(),
      NOW()
    );
  END IF;
END $$;

