-- ============================================================================
-- Born Of God Ministries — Database schema
-- Run in the Supabase SQL Editor. Contains NO demo/seed content.
-- Security model: public can READ published content and SUBMIT prayers /
-- newsletter sign-ups. All content writes require an admin (see `admins`).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Admin allow-list + helper
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email      TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
-- An admin may read their own row (used by the app to confirm admin status).
DROP POLICY IF EXISTS "Admins read own row" ON admins;
CREATE POLICY "Admins read own row" ON admins FOR SELECT USING (auth.uid() = user_id);

-- SECURITY DEFINER so RLS policies can check membership without recursion.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.admins WHERE user_id = auth.uid());
$$;

-- ---------------------------------------------------------------------------
-- Homepage content (single row, id = 1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS homepage_content (
  id               INT PRIMARY KEY DEFAULT 1,
  stats_churches   TEXT NOT NULL,
  stats_pastors    TEXT NOT NULL,
  stats_lives      TEXT NOT NULL,
  stats_countries  TEXT NOT NULL,
  hero_headline    TEXT NOT NULL,
  hero_subheadline TEXT NOT NULL,
  hero_image_url   TEXT NOT NULL,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE homepage_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read homepage_content" ON homepage_content;
DROP POLICY IF EXISTS "admin write homepage_content" ON homepage_content;
CREATE POLICY "public read homepage_content" ON homepage_content FOR SELECT USING (true);
CREATE POLICY "admin write homepage_content" ON homepage_content FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
  id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title       TEXT NOT NULL,
  date        TEXT NOT NULL,
  time        TEXT NOT NULL,
  location    TEXT NOT NULL,
  description TEXT NOT NULL,
  is_major    BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read events" ON events;
DROP POLICY IF EXISTS "admin write events" ON events;
CREATE POLICY "public read events" ON events FOR SELECT USING (true);
CREATE POLICY "admin write events" ON events FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Sermons
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sermons (
  id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title       TEXT NOT NULL,
  speaker     TEXT NOT NULL,
  date        TEXT,
  duration    TEXT,
  "youtubeId" TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE sermons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read sermons" ON sermons;
DROP POLICY IF EXISTS "admin write sermons" ON sermons;
CREATE POLICY "public read sermons" ON sermons FOR SELECT USING (true);
CREATE POLICY "admin write sermons" ON sermons FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Books (library). file_url = downloadable asset in the `media` bucket.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS books (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  author      TEXT NOT NULL,
  category    TEXT,
  pages       INT,
  downloads   TEXT,
  format      TEXT,
  description TEXT,
  cover       TEXT,
  file_url    TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE books ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read books" ON books;
DROP POLICY IF EXISTS "admin write books" ON books;
CREATE POLICY "public read books" ON books FOR SELECT USING (true);
CREATE POLICY "admin write books" ON books FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Prayer requests. PUBLIC may submit; only admins may read/update/delete
-- (requests are private pastoral data).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prayers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  request    TEXT NOT NULL,
  branch     TEXT,
  status     TEXT NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE prayers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public submit prayers" ON prayers;
DROP POLICY IF EXISTS "admin read prayers" ON prayers;
DROP POLICY IF EXISTS "admin manage prayers" ON prayers;
CREATE POLICY "public submit prayers" ON prayers FOR INSERT WITH CHECK (true);
CREATE POLICY "admin read prayers" ON prayers FOR SELECT USING (public.is_admin());
CREATE POLICY "admin manage prayers" ON prayers FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "admin delete prayers" ON prayers;
CREATE POLICY "admin delete prayers" ON prayers FOR DELETE USING (public.is_admin());

-- ---------------------------------------------------------------------------
-- Church branches
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS branches (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  location   TEXT,
  pastor     TEXT,
  members    INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read branches" ON branches;
DROP POLICY IF EXISTS "admin write branches" ON branches;
CREATE POLICY "public read branches" ON branches FOR SELECT USING (true);
CREATE POLICY "admin write branches" ON branches FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Leadership (About page)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leadership (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  role       TEXT,
  bio        TEXT,
  image      TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE leadership ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read leadership" ON leadership;
DROP POLICY IF EXISTS "admin write leadership" ON leadership;
CREATE POLICY "public read leadership" ON leadership FOR SELECT USING (true);
CREATE POLICY "admin write leadership" ON leadership FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Testimonials (homepage)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS testimonials (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  location   TEXT,
  quote      TEXT NOT NULL,
  image      TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read testimonials" ON testimonials;
DROP POLICY IF EXISTS "admin write testimonials" ON testimonials;
CREATE POLICY "public read testimonials" ON testimonials FOR SELECT USING (true);
CREATE POLICY "admin write testimonials" ON testimonials FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------------------
-- Newsletter subscribers. PUBLIC may subscribe; only admins may read/delete.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscribers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public subscribe" ON subscribers;
DROP POLICY IF EXISTS "admin read subscribers" ON subscribers;
DROP POLICY IF EXISTS "admin delete subscribers" ON subscribers;
CREATE POLICY "public subscribe" ON subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "admin read subscribers" ON subscribers FOR SELECT USING (public.is_admin());
CREATE POLICY "admin delete subscribers" ON subscribers FOR DELETE USING (public.is_admin());

-- ---------------------------------------------------------------------------
-- Storage bucket for media (covers, book files, hero image, photos)
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public) VALUES ('media', 'media', true)
ON CONFLICT DO NOTHING;

DROP POLICY IF EXISTS "public read media" ON storage.objects;
DROP POLICY IF EXISTS "admin write media" ON storage.objects;
CREATE POLICY "public read media" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "admin write media" ON storage.objects FOR ALL
  USING (bucket_id = 'media' AND public.is_admin())
  WITH CHECK (bucket_id = 'media' AND public.is_admin());

-- ============================================================================
-- BOOTSTRAP AN ADMIN
-- 1. Create the user in Supabase Dashboard → Authentication → Users
--    (Add user → set email + password → confirm the email).
-- 2. Grant admin by inserting their auth user id here:
--
--    INSERT INTO admins (user_id, email)
--    SELECT id, email FROM auth.users WHERE email = 'you@yourchurch.org'
--    ON CONFLICT (user_id) DO NOTHING;
--
-- Disable public sign-ups in Dashboard → Authentication → Providers → Email
-- so only invited users can authenticate.
-- ============================================================================
